language: python

python:
    - "2.7"
    - "3.6"

before_install:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "No pull requests can be sent to the master branch" 1>&2;
        exit 1;
      fi
    - pip install codecov

install:
    - python scripts/install

script: python scripts/run-tests