language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" != "develop" ]; then
        echo "Pull requests to Master branch can only originate from the develop branch" 1>&2;
        exit 1;
      fi
    - pip install codecov

install:
    - python scripts/install

script:
    - python scripts/run-tests

after_success:
    - codecov
